=== DPGAlliance/publicgoods-candidates/nominee-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "",
  "$comment": "Digital Public Good Metaschema: JSON Schema",
  "title": "Digital Public Good",
  "type": "object",
  "required": [
    "name",
    "description",
    "license",
    "organizations",
    "SDGs",
    "type",
    "stage"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the Digital Public Good. Full name, no initialisms, no acronyms."
    },
    "aliases": {
      "type": "array",
      "description": "Abbreviations, initialisms, or alternate names for Digital Public Good, where relevant.",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string",
      "description": "Concise 1-line description of Digital Public Good."
    },
    "website": {
      "type": "string",
      "description": "Public website for the Digital Public Good."
    },
    "license": {
      "type": "array",
      "description": "Digital Public Goodss must use an open license. Please identify which of these approved open licenses this project uses:",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "required": [
          "spdx",
          "licenseURL"
        ],
        "properties": {
          "spdx": {
            "type": "string",
            "description": "SDPX identifier for this license",
            "enum": [
              "0BSD",
              "AAL",
              "AFL-3.0",
              "AGPL-3.0",
              "Apache-1.1",
              "Apache-2.0",
              "APL-1.0",
              "APSL-2.0",
              "Artistic-1.0",
              "Artistic-2.0",
              "BSD-1-Clause",
              "BSD-2-Clause",
              "BSD-2-Clause-Patent",
              "BSD-3-Clause",
              "BSD-3-Clause-LBNL",
              "BSL-1.0",
              "CAL-1.0",
              "CAL-1.0-Combined-Work-Exception",
              "CATOSL-1.1",
              "CC-BY-1.0",
              "CC-BY-2.0",
              "CC-BY-2.5",
              "CC-BY-3.0",
              "CC-BY-3.0-AT",
              "CC-BY-3.0-US",
              "CC-BY-4.0",
              "CC-BY-NC-1.0",
              "CC-BY-NC-2.0",
              "CC-BY-NC-2.5",
              "CC-BY-NC-3.0",
              "CC-BY-NC-3.0-US",
              "CC-BY-NC-4.0",
              "CC-BY-NC-SA-1.0",
              "CC-BY-NC-SA-2.0",
              "CC-BY-NC-SA-2.5",
              "CC-BY-NC-SA-3.0",
              "CC-BY-NC-SA-3.0-US",
              "CC-BY-NC-SA-4.0",
              "CC-BY-SA-1.0",
              "CC-BY-SA-2.0",
              "CC-BY-SA-2.5",
              "CC-BY-SA-3.0",
              "CC-BY-SA-3.0-AT",
              "CC-BY-SA-3.0-US",
              "CC-BY-SA-4.0",
              "CC0-1.0",
              "CDDL-1.0",
              "CECILL-2.1",
              "CNRI-Python",
              "CPAL-1.0",
              "CPL-1.0",
              "ECL-1.0",
              "ECL-2.0",
              "EFL-1.0",
              "EFL-2.0",
              "Entessa",
              "EPL-1.0",
              "EPL-2.0",
              "EUDatagrid",
              "EUPL-1.2",
              "Fair",
              "Frameworx-1.0",
              "GPL-2.0",
              "GPL-3.0",
              "HPND",
              "IPA",
              "IPL-1.0",
              "ISC",
              "LGPL-2.1",
              "LGPL-3.0",
              "LiLiQ-P-1.1",
              "LiLiQ-R-1.1",
              "LiLiQ-Rplus-1.1",
              "LPL-1.0",
              "LPL-1.02",
              "LPPL-1.3c",
              "MirOS",
              "MIT",
              "MIT-0",
              "Motosoto",
              "MPL-1.0",
              "MPL-1.1",
              "MPL-2.0",
              "MPL-2.0-no-copyleft-exception",
              "MS-PL",
              "MS-RL",
              "MulanPSL-2.0",
              "Multics",
              "NASA-1.3",
              "Naumen",
              "NCSA",
              "NGPL",
              "Nokia",
              "NPOSL-3.0",
              "NTP",
              "OCLC-2.0",
              "ODbL-1.0",
              "ODC-By-1.0 ",
              "OFL-1.1",
              "OFL-1.1-no-RFN",
              "OFL-1.1-RFN",
              "OGTSL",
              "OLDAP-2.8",
              "OSET-PL-2.1",
              "OSL-1.0",
              "OSL-2.1",
              "OSL-3.0",
              "PDDL-1.0",
              "PHP-3.0",
              "PHP-3.01",
              "PostgreSQL",
              "Python-2.0",
              "QPL-1.0",
              "RPL-1.1",
              "RPL-1.5",
              "RPSL-1.0",
              "RSCPL",
              "SimPL-2.0",
              "Sleepycat",
              "SPL-1.0",
              "UCL-1.0",
              "Unicode-DFS-2015",
              "Unicode-DFS-2016",
              "Unlicense",
              "UPL-1.0",
              "VSL-1.0",
              "W3C",
              "Watcom-1.0",
              "Xnet",
              "wxWindows",
              "Zlib",
              "ZPL-2.0"
            ]
          },
          "licenseURL": {
            "type": "string",
            "description": "Please link to where the license is indicated for this project:"
          }
        }
      }
    },
    "SDGs": {
      "type": "array",
      "description": "Please identify which of the Sustainable Development Goals this project is relevant to:",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "required": [
          "SDGNumber"
        ],
        "properties": {
          "SDGNumber": {
            "type": "number",
            "description": "Number of the Sustainable Development Goal",
            "enum": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17
            ]
          },
          "evidenceText": {
            "type": "string",
            "description": "Please supply information to support this relevance."
          },
          "evidenceURL": {
            "type": "string",
            "description": "Please supply links to support this relevance."
          }
        }
      }
    },
    "sectors": {
      "type": "array",
      "description": "List of sectors that this Global Digital Public Good addresses.",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "Advocacy",
          "Agriculture",
          "Anti-corruption",
          "Big Data",
          "Business Advocacy",
          "Capacity Development",
          "Centers of Excellence",
          "Civil society",
          "Climate",
          "Communication",
          "Conflict Resolution",
          "Consulting",
          "Corporate Partnerships",
          "Corporation and Business Management",
          "Data Collection",
          "Data Management & Policy",
          "Data Security",
          "Demobilization & Reintegration",
          "Democracy",
          "Development Impact",
          "Digital Development",
          "Digital/Data/Tech",
          "Disarmament",
          "Economics/Finance",
          "Education",
          "Emergency Response",
          "Employment",
          "Energy",
          "Engineering",
          "Enterprise Ecosystems",
          "Entertainment",
          "Environment",
          "Fair & Responsible Media",
          "Female Genital Mutilation",
          "Food",
          "Fragile States",
          "Gender and Minority Groups",
          "Governance",
          "Health",
          "Humanitarian",
          "Hunger",
          "Infrastructure",
          "Justice",
          "Livelihoods",
          "Logistics",
          "Management",
          "Media",
          "Membership Associations",
          "Midwifery",
          "Natural Resource Conflicts",
          "NGO",
          "Nutrition",
          "Peace",
          "Platform creation",
          "Religious Engagement",
          "Research",
          "Resource Management",
          "Security",
          "Social Protection",
          "Stability",
          "Supply Chain Solutions",
          "Sustainability",
          "Sustainable Cities",
          "Training & Employment",
          "Transition",
          "Transparency & Accountability",
          "Travel and Hospitality",
          "Violent Extremism",
          "Water and Sanitation",
          "Workforce",
          "World Population",
          "Youth"
        ]
      }
    },
    "type": {
      "type": "array",
      "description": "What category best describes this project?",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "software",
          "data",
          "content",
          "standard",
          "aimodel"
        ]
      }
    },
    "repositoryURL": {
      "type": "string",
      "description": "Link to Github (or other) repository."
    },
    "organizations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the organization"
          },
          "website": {
            "type": "string",
            "description": "Website of the organization"
          },
          "org_type": {
            "type": "string",
            "description": "Type of organization",
            "enum": [
              "owner",
              "maintainer",
              "funder",
              "implementer"
            ]
          },
          "contact_name": {
            "type": "string",
            "description": "Name of contact individual in the organization"
          },
          "contact_email": {
            "type": "string",
            "description": "Email for contact individual in the organization"
          }
        }
      }
    },
    "stage": {
      "type": "string",
      "description": "Screening stage of Digital Public Good",
      "enum": [
        "nominee",
        "candidate",
        "DPG"
      ]
    }
  }
}

=== DPGAlliance/publicgoods-candidates/nominees/operation-code-front-end.json
{
  "name": "Operation Code Front-End",
  "description": "Re-implementation of Operation Code's front-end with best practices, SEO, and performance in mind.",
  "website": "https://operation-code.now.sh",
  "license": [
    {
      "spdx": "MIT",
      "licenseURL": "https://github.com/OperationCode/front-end/blob/master/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 4
    },
    {
      "SDGNumber": 10
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/OperationCode/front-end",
  "organizations": [
    {
      "name": "Operation Code",
      "website": "https://www.operationcode.org",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/green-button.json
{
  "name": "Green Button",
  "description": "Green Button is a secure way to get your energy usage information electronically.",
  "website": "https://green-button.github.io",
  "license": [
    {
      "spdx": "Apache-2.0",
      "licenseURL": "https://github.com/GreenButtonAlliance/OpenESPI-Common-java/blob/master/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 7
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/GreenButtonAlliance/OpenESPI-Common-java",
  "organizations": [
    {
      "name": "Green Button Alliance",
      "website": "https://www.greenbuttonalliance.org/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/housing-vacancy-bot.json
{
  "name": "Housing Vacancy Bot",
  "description": "A Telegram bot that allows housing officials/owners to report vacancy to a central source and allows health works/government officials to consume that information.",
  "website": "https://ethiocovid19rt.com/",
  "license": [
    {
      "spdx": "MIT",
      "licenseURL": "https://github.com/africa-covid-19-response-toolkit/housing-vacancy-bot/blob/master/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 3,
      "evidenceURL": "https://medium.com/africa-covid-19-response-toolkit/introducing-the-open-source-africa-covid-19-response-toolkit-6d4a571027a8"
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/africa-covid-19-response-toolkit/housing-vacancy-bot/blob/master/LICENSE",
  "organizations": [
    {
      "name": "Ethiopia COVID-19 Response Team",
      "website": "https://ethiocovid19rt.com/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/cnb-guatemala.json
{
  "name": "CNB Guatemala",
  "description": "A digital online version of the Guatemalan National Basic Curriculum, aligned open educational resources and other teacher development resources.",
  "website": "http://cnbGuatemala.org",
  "license": [
    {
      "spdx": "CC-BY-SA-4.0",
      "licenseURL": "http://cnbguatemala.org/wiki/CNB:Derechos_de_autor"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 4,
      "evidenceURL": "http://cnbguatemala.org/wiki/Ayuda:Website_tour_(English), https://www.prensalibre.com/guatemala/comunitario/curriculo-nacional-base-en-linea-aporta-herramientas-a-docentes/"
    },
    {
      "SDGNumber": 10,
      "evidenceURL": "http://cnbguatemala.org/wiki/Ayuda:Website_tour_(English), https://www.prensalibre.com/guatemala/comunitario/curriculo-nacional-base-en-linea-aporta-herramientas-a-docentes/"
    }
  ],
  "sectors": [],
  "type": [
    "data",
    "content"
  ],
  "organizations": [
    {
      "name": "Online Learning Initiative",
      "website": "http://online-learning-initiative.org",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/global-healthsites-mapping-project.json
{
  "name": "Global Healthsites Mapping Project",
  "description": "Healthsites is an innovative Global initiative improving Global baseline health facility data by using OpenStreetMap as the data store.",
  "website": "https://healthsites.io/",
  "license": [
    {
      "spdx": "BSD-3-Clause",
      "licenseURL": "https://github.com/healthsites/healthsites/blob/master/LICENSE-CODE.txt"
    },
    {
      "spdx": "ODbL-1.0",
      "licenseURL": "https://github.com/healthsites/healthsites/wiki/Data"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 3,
      "evidenceText": "In a time of crisis, such as the COVID-19 disease outbreak, there is a rush to establish accurate health care location data that can be used to support people on the ground. This has been demonstrated by events such as the Haiti earthquake and the Ebola epidemic in West Africa. As a result valuable time is wasted establishing accurate and accessible baseline data. Healthsites.io establishes this data and the tools necessary to upload, manage and make the data easily accessible",
      "evidenceURL": "https://covid19innovationhub.org/innovation/the-global-healthsites-mapping-project, \nhttps://wiki.openstreetmap.org/wiki/Global_Healthsites_Mapping_Project, \nhttps://www.data4sdgs.org/partner/global-healthsites-mapping-project"
    }
  ],
  "sectors": [
    "Health"
  ],
  "type": [
    "software",
    "data"
  ],
  "repositoryURL": "https://github.com/healthsites/healthsites",
  "organizations": [
    {
      "name": "OPEN HEALTHSITE CONSULTING LTD",
      "website": "https://healthsites.io",
      "org_type": "owner"
    }
  ],
  "stage": "DPG"
}

=== DPGAlliance/publicgoods-candidates/nominees/apache-ctakes.json
{
  "name": "Apache cTAKES",
  "aliases": [
    "Apache clinical Text Analysis and Knowledge Extraction System"
  ],
  "description": "Apache cTAKES is a natural language processing system for extraction of information from electronic medical record clinical free-text.",
  "website": "http://ctakes.apache.org/",
  "license": [
    {
      "spdx": "Apache-2.0",
      "licenseURL": "https://github.com/apache/ctakes/blob/trunk/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 3,
      "evidenceURL": "https://www.openhealthnews.com/content/apachecon-2020-features-natural-language-processing-electronic-medical-records-dedicated-tra"
    },
    {
      "SDGNumber": 9,
      "evidenceURL": "https://www.openhealthnews.com/content/apachecon-2020-features-natural-language-processing-electronic-medical-records-dedicated-tra"
    }
  ],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/apache/ctakes",
  "organizations": [
    {
      "name": "The Apache Software Foundation",
      "website": "https://apache.org",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/nvda.json
{
  "name": "NVDA",
  "description": "NVDA allows blind and vision impaired people to access and interact with the Windows operating system and many third party applications.",
  "website": "",
  "license": [
    {
      "spdx": "GPL-2.0",
      "licenseURL": "https://github.com/nvaccess/nvda/blob/master/copying.txt"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 3
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/nvaccess/nvda",
  "organizations": [
    {
      "name": "NVAccess",
      "website": "https://www.nvaccess.org/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/orange.json
{
  "name": "Orange",
  "description": "Orange is an open-source data visualization, machine learning and data mining toolkit. It features a visual programming front-end for explorative rapid qualitative data analysis and interactive data visualization.",
  "website": "https://orangedatamining.com/",
  "license": [
    {
      "spdx": "GPL-3.0",
      "licenseURL": "https://github.com/biolab/orange3/blob/master/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 3,
      "evidenceURL": "https://core.ac.uk/download/pdf/231161571.pdf"
    },
    {
      "SDGNumber": 9,
      "evidenceURL": "https://orangedatamining.com/home/interactive_data_visualization/"
    }
  ],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/biolab/orange3",
  "organizations": [
    {
      "name": "University of Ljubljana, Faculty of Computer and Information Science, Bioinformatics Laboratory",
      "website": "https://www.fri.uni-lj.si/en/laboratory/biolab",
      "org_type": "owner",
      "contact_email": "info@biolab.si"
    }
  ],
  "stage": "nominee"
}
