=== DPGAlliance/publicgoods-candidates/nominee-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "",
  "$comment": "Digital Public Good Metaschema: JSON Schema",
  "title": "Digital Public Good",
  "type": "object",
  "required": [
    "name",
    "description",
    "license",
    "organizations",
    "SDGs",
    "type",
    "stage"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the Digital Public Good. Full name, no initialisms, no acronyms."
    },
    "aliases": {
      "type": "array",
      "description": "Abbreviations, initialisms, or alternate names for Digital Public Good, where relevant.",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string",
      "description": "Concise 1-line description of Digital Public Good."
    },
    "website": {
      "type": "string",
      "description": "Public website for the Digital Public Good."
    },
    "license": {
      "type": "array",
      "description": "Digital Public Goodss must use an open license. Please identify which of these approved open licenses this project uses:",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "required": [
          "spdx",
          "licenseURL"
        ],
        "properties": {
          "spdx": {
            "type": "string",
            "description": "SDPX identifier for this license",
            "enum": [
              "0BSD",
              "AAL",
              "AFL-3.0",
              "AGPL-3.0",
              "Apache-1.1",
              "Apache-2.0",
              "APL-1.0",
              "APSL-2.0",
              "Artistic-1.0",
              "Artistic-2.0",
              "BSD-1-Clause",
              "BSD-2-Clause",
              "BSD-2-Clause-Patent",
              "BSD-3-Clause",
              "BSD-3-Clause-LBNL",
              "BSL-1.0",
              "CAL-1.0",
              "CAL-1.0-Combined-Work-Exception",
              "CATOSL-1.1",
              "CC-BY-1.0",
              "CC-BY-2.0",
              "CC-BY-2.5",
              "CC-BY-3.0",
              "CC-BY-3.0-AT",
              "CC-BY-3.0-US",
              "CC-BY-4.0",
              "CC-BY-NC-1.0",
              "CC-BY-NC-2.0",
              "CC-BY-NC-2.5",
              "CC-BY-NC-3.0",
              "CC-BY-NC-3.0-US",
              "CC-BY-NC-4.0",
              "CC-BY-NC-SA-1.0",
              "CC-BY-NC-SA-2.0",
              "CC-BY-NC-SA-2.5",
              "CC-BY-NC-SA-3.0",
              "CC-BY-NC-SA-3.0-US",
              "CC-BY-NC-SA-4.0",
              "CC-BY-SA-1.0",
              "CC-BY-SA-2.0",
              "CC-BY-SA-2.5",
              "CC-BY-SA-3.0",
              "CC-BY-SA-3.0-AT",
              "CC-BY-SA-3.0-US",
              "CC-BY-SA-4.0",
              "CC0-1.0",
              "CDDL-1.0",
              "CECILL-2.1",
              "CNRI-Python",
              "CPAL-1.0",
              "CPL-1.0",
              "ECL-1.0",
              "ECL-2.0",
              "EFL-1.0",
              "EFL-2.0",
              "Entessa",
              "EPL-1.0",
              "EPL-2.0",
              "EUDatagrid",
              "EUPL-1.2",
              "Fair",
              "Frameworx-1.0",
              "GPL-2.0",
              "GPL-3.0",
              "HPND",
              "IPA",
              "IPL-1.0",
              "ISC",
              "LGPL-2.1",
              "LGPL-3.0",
              "LiLiQ-P-1.1",
              "LiLiQ-R-1.1",
              "LiLiQ-Rplus-1.1",
              "LPL-1.0",
              "LPL-1.02",
              "LPPL-1.3c",
              "MirOS",
              "MIT",
              "MIT-0",
              "Motosoto",
              "MPL-1.0",
              "MPL-1.1",
              "MPL-2.0",
              "MPL-2.0-no-copyleft-exception",
              "MS-PL",
              "MS-RL",
              "MulanPSL-2.0",
              "Multics",
              "NASA-1.3",
              "Naumen",
              "NCSA",
              "NGPL",
              "Nokia",
              "NPOSL-3.0",
              "NTP",
              "OCLC-2.0",
              "ODbL-1.0",
              "ODC-By-1.0 ",
              "OFL-1.1",
              "OFL-1.1-no-RFN",
              "OFL-1.1-RFN",
              "OGTSL",
              "OLDAP-2.8",
              "OSET-PL-2.1",
              "OSL-1.0",
              "OSL-2.1",
              "OSL-3.0",
              "PDDL-1.0",
              "PHP-3.0",
              "PHP-3.01",
              "PostgreSQL",
              "Python-2.0",
              "QPL-1.0",
              "RPL-1.1",
              "RPL-1.5",
              "RPSL-1.0",
              "RSCPL",
              "SimPL-2.0",
              "Sleepycat",
              "SPL-1.0",
              "UCL-1.0",
              "Unicode-DFS-2015",
              "Unicode-DFS-2016",
              "Unlicense",
              "UPL-1.0",
              "VSL-1.0",
              "W3C",
              "Watcom-1.0",
              "Xnet",
              "wxWindows",
              "Zlib",
              "ZPL-2.0"
            ]
          },
          "licenseURL": {
            "type": "string",
            "description": "Please link to where the license is indicated for this project:"
          }
        }
      }
    },
    "SDGs": {
      "type": "array",
      "description": "Please identify which of the Sustainable Development Goals this project is relevant to:",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "required": [
          "SDGNumber"
        ],
        "properties": {
          "SDGNumber": {
            "type": "number",
            "description": "Number of the Sustainable Development Goal",
            "enum": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17
            ]
          },
          "evidenceText": {
            "type": "string",
            "description": "Please supply information to support this relevance."
          },
          "evidenceURL": {
            "type": "string",
            "description": "Please supply links to support this relevance."
          }
        }
      }
    },
    "sectors": {
      "type": "array",
      "description": "List of sectors that this Global Digital Public Good addresses.",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "Advocacy",
          "Agriculture",
          "Anti-corruption",
          "Big Data",
          "Business Advocacy",
          "Capacity Development",
          "Centers of Excellence",
          "Civil society",
          "Climate",
          "Communication",
          "Conflict Resolution",
          "Consulting",
          "Corporate Partnerships",
          "Corporation and Business Management",
          "Data Collection",
          "Data Management & Policy",
          "Data Security",
          "Demobilization & Reintegration",
          "Democracy",
          "Development Impact",
          "Digital Development",
          "Digital/Data/Tech",
          "Disarmament",
          "Economics/Finance",
          "Education",
          "Emergency Response",
          "Employment",
          "Energy",
          "Engineering",
          "Enterprise Ecosystems",
          "Entertainment",
          "Environment",
          "Fair & Responsible Media",
          "Female Genital Mutilation",
          "Food",
          "Fragile States",
          "Gender and Minority Groups",
          "Governance",
          "Health",
          "Humanitarian",
          "Hunger",
          "Infrastructure",
          "Justice",
          "Livelihoods",
          "Logistics",
          "Management",
          "Media",
          "Membership Associations",
          "Midwifery",
          "Natural Resource Conflicts",
          "NGO",
          "Nutrition",
          "Peace",
          "Platform creation",
          "Religious Engagement",
          "Research",
          "Resource Management",
          "Security",
          "Social Protection",
          "Stability",
          "Supply Chain Solutions",
          "Sustainability",
          "Sustainable Cities",
          "Training & Employment",
          "Transition",
          "Transparency & Accountability",
          "Travel and Hospitality",
          "Violent Extremism",
          "Water and Sanitation",
          "Workforce",
          "World Population",
          "Youth"
        ]
      }
    },
    "type": {
      "type": "array",
      "description": "What category best describes this project?",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "software",
          "data",
          "content",
          "standard",
          "aimodel"
        ]
      }
    },
    "repositoryURL": {
      "type": "string",
      "description": "Link to Github (or other) repository."
    },
    "organizations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the organization"
          },
          "website": {
            "type": "string",
            "description": "Website of the organization"
          },
          "org_type": {
            "type": "string",
            "description": "Type of organization",
            "enum": [
              "owner",
              "maintainer",
              "funder",
              "implementer"
            ]
          },
          "contact_name": {
            "type": "string",
            "description": "Name of contact individual in the organization"
          },
          "contact_email": {
            "type": "string",
            "description": "Email for contact individual in the organization"
          }
        }
      }
    },
    "stage": {
      "type": "string",
      "description": "Screening stage of Digital Public Good",
      "enum": [
        "nominee",
        "candidate",
        "DPG"
      ]
    }
  }
}

=== DPGAlliance/publicgoods-candidates/nominees/healthsites.io.json
{
  "name": "HealthSites.io",
  "description": "Healthsites is a framework for capturing, publishing and sharing critical health and sanitation related data to help make these facilities more accessible and relevant to the communities they serve.",
  "website": "https://healthsites.io",
  "license": [
    {
      "spdx": "ODbL-1.0",
      "licenseURL": "https://github.com/healthsites/healthsites/blob/master/LICENSE-DATA.txt"
    },
    {
      "spdx": "BSD-3-Clause",
      "licenseURL": "https://github.com/healthsites/healthsites/blob/master/LICENSE-CODE.txt"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 3
    },
    {
      "SDGNumber": 16
    },
    {
      "SDGNumber": 17
    }
  ],
  "sectors": [],
  "type": [
    "software",
    "data"
  ],
  "repositoryURL": "https://github.com/healthsites/healthsites",
  "organizations": [
    {
      "name": "HealthSites.io",
      "website": "https://healthsites.io",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/emoncms.json
{
  "name": "Emoncms",
  "description": "Emoncms is an open-source web application for processing, logging and visualising energy, temperature and other environmental data.",
  "website": "https://emoncms.org/",
  "license": [
    {
      "spdx": "AGPL-3.0",
      "licenseURL": "https://github.com/emoncms/emoncms/blob/master/LICENSE.txt"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 7,
      "evidenceText": "Emoncms is an open-source web application for processing, logging and visualising energy, temperature and other environmental data. It is a part of the OpenEnergyMonitor project. It helps users understand energy, explore the context of renewable energy and zero carbon"
    }
  ],
  "sectors": [
    "Energy"
  ],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/emoncms/emoncms",
  "organizations": [
    {
      "name": "OpenEnergyMonitor",
      "website": "https://openenergymonitor.org/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/openbci-gui.json
{
  "name": "OpenBCI GUI",
  "description": "OpenBCI stands for open-source brain-computer interface (BCI). We provide anyone with a computer, the tools necessary to sample the electrical activity of their body.",
  "website": "https://openbci.com/",
  "license": [
    {
      "spdx": "MIT",
      "licenseURL": "https://github.com/OpenBCI/OpenBCI_GUI/blob/master/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 3,
      "evidenceText": "OpenBCI specializes in creating low-cost, high-quality biosensing hardware for brain computer interfacing. Our arduino compatible biosensing boards provide high resolution imaging and recording of EMG, ECG, and EEG signals. Our devices have been used by researchers, makers, and hobbyists in over 80 countries as brain computer interfaces to power machines and map brain activity. OpenBCI headsets, boards, sensors and electrodes allow anyone interested in biosensing and neurofeedback to purchase high quality equipment at affordable prices."
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/OpenBCI/OpenBCI_GUI",
  "organizations": [
    {
      "name": "Open Source Brain-Computer Interfacing",
      "website": "https://openbci.com/",
      "org_type": "owner",
      "contact_email": "contact@openbci.com"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/internal-dashboard.json
{
  "name": "Internal Dashboard",
  "description": "Internal dashboard for officials to get real time data and updates on COVID-19 on surveillance, case tracking, and monitoring.",
  "website": "https://ethiocovid19rt.com/",
  "license": [
    {
      "spdx": "MIT",
      "licenseURL": "https://github.com/africa-covid-19-response-toolkit/internal-dashboard/blob/master/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 3,
      "evidenceURL": "https://medium.com/africa-covid-19-response-toolkit/africa-covid-19-response-toolkit-dashboard-c5d872932a9"
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/africa-covid-19-response-toolkit/internal-dashboard",
  "organizations": [
    {
      "name": "Ethiopia COVID-19 Response Team",
      "website": "https://ethiocovid19rt.com/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/viame.json
{
  "name": "VIAME",
  "description": "A do-it-yourself AI system for analyzing imagery and video, orginally targeting marine species analysis.",
  "website": "https://www.viametoolkit.org/",
  "license": [
    {
      "spdx": "BSD-3-Clause",
      "licenseURL": "https://github.com/VIAME/VIAME/blob/master/LICENSE.txt"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 14,
      "evidenceText": "VIAME provides a crucial platform for the development of ML for various applications in the marine environment ranging from underwater visual fish surveys to aerial surveys of marine mammals.",
      "evidenceURL": "https://spo.nmfs.noaa.gov/sites/default/files/TMSPO194.pdf"
    }
  ],
  "sectors": [
    "Data Collection",
    "Digital Development",
    "Environment",
    "Research"
  ],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/VIAME/VIAME",
  "organizations": [
    {
      "name": "VIAME",
      "website": "https://www.viametoolkit.org/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/webpack.json
{
  "name": "webpack",
  "description": "A bundler for javascript and friends. Packs many modules into a few bundled assets. Code Splitting allows for loading parts of the application on demand. Through \"loaders\", modules can be CommonJs, AMD, ES6 modules, CSS, Images, JSON, Coffeescript, LESS, ... and your custom stuff.",
  "website": "https://webpack.js.org/",
  "license": [
    {
      "spdx": "MIT",
      "licenseURL": "https://github.com/webpack/webpack/blob/master/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 9
    }
  ],
  "sectors": [
    "Digital/Data/Tech"
  ],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/webpack/webpack/",
  "organizations": [
    {
      "name": "webpack",
      "website": "https://webpack.js.org/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/acrt-surveillance-form.json
{
    "name": "ACRT Surveillance Form",
    "description": "Online forms for reporting rumored COVID-19 cases.",
    "website": "http://forms.ethiopia-covid19.com/",
    "license": [
      {
        "spdx": "MIT",
        "licenseURL": "https://github.com/africa-covid-19-response-toolkit/surveillance-forms/blob/master/LICENSE"
      }
    ],
    "SDGs": [
      {
        "SDGNumber": 3,
        "evidenceURL": "https://medium.com/africa-covid-19-response-toolkit/introducing-the-open-source-africa-covid-19-response-toolkit-6d4a571027a8"
      }
    ],
    "type": [
      "software"
    ],
    "repositoryURL": "https://github.com/africa-covid-19-response-toolkit/surveillance-forms",
    "organizations": [
      {
        "name": "Ethiopia COVID-19 Response Team",
        "website": "https://ethiocovid19rt.com/",
        "org_type": "owner",
        "contact_email": "acrt@ethiocovid19rt.com"
      }
    ],
    "stage": "nominee"
  }

=== DPGAlliance/publicgoods-candidates/nominees/vista.json
{
  "name": "VistA",
  "description": "Electronic Health Record systems (EHR) are essential to improving health quality and managing health care delivery, whether in a large health system, hospital, or primary care clinic. The U.S. Department of Veterans Affairs (VA) has developed and continues to maintain a robust EHR known as VistA - the Veterans Health Information Systems and Technology Architecture. This system was designed and developed to support a high-quality medical care environment for the military veterans in the United States.",
  "website": "https://worldvista.org/AboutVistA",
  "license": [
    {
      "spdx": "Apache-2.0",
      "licenseURL": "https://github.com/WorldVistA/VistA/blob/master/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 3,
      "evidenceURL": "https://www.nytimes.com/2007/05/30/opinion/30goetz.html?ex=1338177600&en=4b9b74b9874cad7f&ei=5124&partner=permalink&exprod=permalink"
    }
  ],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/WorldVistA/VistA",
  "organizations": [
    {
      "name": "WorldVistA",
      "website": "https://www.worldvista.org/",
      "org_type": "owner",
      "contact_email": "info@worldvista.org"
    }
  ],
  "stage": "nominee"
}
