=== DPGAlliance/publicgoods-candidates/nominee-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "",
  "$comment": "Digital Public Good Metaschema: JSON Schema",
  "title": "Digital Public Good",
  "type": "object",
  "required": [
    "name",
    "description",
    "license",
    "organizations",
    "SDGs",
    "type",
    "stage"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the Digital Public Good. Full name, no initialisms, no acronyms."
    },
    "aliases": {
      "type": "array",
      "description": "Abbreviations, initialisms, or alternate names for Digital Public Good, where relevant.",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string",
      "description": "Concise 1-line description of Digital Public Good."
    },
    "website": {
      "type": "string",
      "description": "Public website for the Digital Public Good."
    },
    "license": {
      "type": "array",
      "description": "Digital Public Goodss must use an open license. Please identify which of these approved open licenses this project uses:",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "required": [
          "spdx",
          "licenseURL"
        ],
        "properties": {
          "spdx": {
            "type": "string",
            "description": "SDPX identifier for this license",
            "enum": [
              "0BSD",
              "AAL",
              "AFL-3.0",
              "AGPL-3.0",
              "Apache-1.1",
              "Apache-2.0",
              "APL-1.0",
              "APSL-2.0",
              "Artistic-1.0",
              "Artistic-2.0",
              "BSD-1-Clause",
              "BSD-2-Clause",
              "BSD-2-Clause-Patent",
              "BSD-3-Clause",
              "BSD-3-Clause-LBNL",
              "BSL-1.0",
              "CAL-1.0",
              "CAL-1.0-Combined-Work-Exception",
              "CATOSL-1.1",
              "CC-BY-1.0",
              "CC-BY-2.0",
              "CC-BY-2.5",
              "CC-BY-3.0",
              "CC-BY-3.0-AT",
              "CC-BY-3.0-US",
              "CC-BY-4.0",
              "CC-BY-NC-1.0",
              "CC-BY-NC-2.0",
              "CC-BY-NC-2.5",
              "CC-BY-NC-3.0",
              "CC-BY-NC-3.0-US",
              "CC-BY-NC-4.0",
              "CC-BY-NC-SA-1.0",
              "CC-BY-NC-SA-2.0",
              "CC-BY-NC-SA-2.5",
              "CC-BY-NC-SA-3.0",
              "CC-BY-NC-SA-3.0-US",
              "CC-BY-NC-SA-4.0",
              "CC-BY-SA-1.0",
              "CC-BY-SA-2.0",
              "CC-BY-SA-2.5",
              "CC-BY-SA-3.0",
              "CC-BY-SA-3.0-AT",
              "CC-BY-SA-3.0-US",
              "CC-BY-SA-4.0",
              "CC0-1.0",
              "CDDL-1.0",
              "CECILL-2.1",
              "CNRI-Python",
              "CPAL-1.0",
              "CPL-1.0",
              "ECL-1.0",
              "ECL-2.0",
              "EFL-1.0",
              "EFL-2.0",
              "Entessa",
              "EPL-1.0",
              "EPL-2.0",
              "EUDatagrid",
              "EUPL-1.2",
              "Fair",
              "Frameworx-1.0",
              "GPL-2.0",
              "GPL-3.0",
              "HPND",
              "IPA",
              "IPL-1.0",
              "ISC",
              "LGPL-2.1",
              "LGPL-3.0",
              "LiLiQ-P-1.1",
              "LiLiQ-R-1.1",
              "LiLiQ-Rplus-1.1",
              "LPL-1.0",
              "LPL-1.02",
              "LPPL-1.3c",
              "MirOS",
              "MIT",
              "MIT-0",
              "Motosoto",
              "MPL-1.0",
              "MPL-1.1",
              "MPL-2.0",
              "MPL-2.0-no-copyleft-exception",
              "MS-PL",
              "MS-RL",
              "MulanPSL-2.0",
              "Multics",
              "NASA-1.3",
              "Naumen",
              "NCSA",
              "NGPL",
              "Nokia",
              "NPOSL-3.0",
              "NTP",
              "OCLC-2.0",
              "ODbL-1.0",
              "ODC-By-1.0 ",
              "OFL-1.1",
              "OFL-1.1-no-RFN",
              "OFL-1.1-RFN",
              "OGTSL",
              "OLDAP-2.8",
              "OSET-PL-2.1",
              "OSL-1.0",
              "OSL-2.1",
              "OSL-3.0",
              "PDDL-1.0",
              "PHP-3.0",
              "PHP-3.01",
              "PostgreSQL",
              "Python-2.0",
              "QPL-1.0",
              "RPL-1.1",
              "RPL-1.5",
              "RPSL-1.0",
              "RSCPL",
              "SimPL-2.0",
              "Sleepycat",
              "SPL-1.0",
              "UCL-1.0",
              "Unicode-DFS-2015",
              "Unicode-DFS-2016",
              "Unlicense",
              "UPL-1.0",
              "VSL-1.0",
              "W3C",
              "Watcom-1.0",
              "Xnet",
              "wxWindows",
              "Zlib",
              "ZPL-2.0"
            ]
          },
          "licenseURL": {
            "type": "string",
            "description": "Please link to where the license is indicated for this project:"
          }
        }
      }
    },
    "SDGs": {
      "type": "array",
      "description": "Please identify which of the Sustainable Development Goals this project is relevant to:",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "required": [
          "SDGNumber"
        ],
        "properties": {
          "SDGNumber": {
            "type": "number",
            "description": "Number of the Sustainable Development Goal",
            "enum": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17
            ]
          },
          "evidenceText": {
            "type": "string",
            "description": "Please supply information to support this relevance."
          },
          "evidenceURL": {
            "type": "string",
            "description": "Please supply links to support this relevance."
          }
        }
      }
    },
    "sectors": {
      "type": "array",
      "description": "List of sectors that this Global Digital Public Good addresses.",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "Advocacy",
          "Agriculture",
          "Anti-corruption",
          "Big Data",
          "Business Advocacy",
          "Capacity Development",
          "Centers of Excellence",
          "Civil society",
          "Climate",
          "Communication",
          "Conflict Resolution",
          "Consulting",
          "Corporate Partnerships",
          "Corporation and Business Management",
          "Data Collection",
          "Data Management & Policy",
          "Data Security",
          "Demobilization & Reintegration",
          "Democracy",
          "Development Impact",
          "Digital Development",
          "Digital/Data/Tech",
          "Disarmament",
          "Economics/Finance",
          "Education",
          "Emergency Response",
          "Employment",
          "Energy",
          "Engineering",
          "Enterprise Ecosystems",
          "Entertainment",
          "Environment",
          "Fair & Responsible Media",
          "Female Genital Mutilation",
          "Food",
          "Fragile States",
          "Gender and Minority Groups",
          "Governance",
          "Health",
          "Humanitarian",
          "Hunger",
          "Infrastructure",
          "Justice",
          "Livelihoods",
          "Logistics",
          "Management",
          "Media",
          "Membership Associations",
          "Midwifery",
          "Natural Resource Conflicts",
          "NGO",
          "Nutrition",
          "Peace",
          "Platform creation",
          "Religious Engagement",
          "Research",
          "Resource Management",
          "Security",
          "Social Protection",
          "Stability",
          "Supply Chain Solutions",
          "Sustainability",
          "Sustainable Cities",
          "Training & Employment",
          "Transition",
          "Transparency & Accountability",
          "Travel and Hospitality",
          "Violent Extremism",
          "Water and Sanitation",
          "Workforce",
          "World Population",
          "Youth"
        ]
      }
    },
    "type": {
      "type": "array",
      "description": "What category best describes this project?",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "software",
          "data",
          "content",
          "standard",
          "aimodel"
        ]
      }
    },
    "repositoryURL": {
      "type": "string",
      "description": "Link to Github (or other) repository."
    },
    "organizations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the organization"
          },
          "website": {
            "type": "string",
            "description": "Website of the organization"
          },
          "org_type": {
            "type": "string",
            "description": "Type of organization",
            "enum": [
              "owner",
              "maintainer",
              "funder",
              "implementer"
            ]
          },
          "contact_name": {
            "type": "string",
            "description": "Name of contact individual in the organization"
          },
          "contact_email": {
            "type": "string",
            "description": "Email for contact individual in the organization"
          }
        }
      }
    },
    "stage": {
      "type": "string",
      "description": "Screening stage of Digital Public Good",
      "enum": [
        "nominee",
        "candidate",
        "DPG"
      ]
    }
  }
}

=== DPGAlliance/publicgoods-candidates/nominees/the-guardian-project-haven.json
{
  "name": "The Guardian Project - Haven",
  "description": "Haven is for people who need a way to protect their personal spaces and possessions without compromising their own privacy, through an Android app and on-device sensors.",
  "website": "",
  "license": [
    {
      "spdx": "GPL-3.0",
      "licenseURL": "https://github.com/guardianproject/haven/blob/master/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 11
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/guardianproject/haven",
  "organizations": [
    {
      "name": "The Guardian Project",
      "website": "https://guardianproject.info/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/eduactiv8.json
{
  "name": "eduActiv8",
  "description": "eduActiv8 is an open source, free educational program for children 3 to about 10 years old. It helps in learning a range of subjects, but mainly focuses on maths",
  "website": "https://www.eduactiv8.org/",
  "license": [
    {
      "spdx": "GPL-3.0",
      "licenseURL": "https://github.com/imiolek-ireneusz/eduActiv8/blob/master/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 4,
      "evidenceText": "eduActiv8 includes activities for building basic math and early literacy skills, including a variety of spelling, matching, and listening activities",
      "evidenceURL": "https://opensource.com/article/19/4/early-literacy-tools"
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/imiolek-ireneusz/eduActiv8",
  "organizations": [
    {
      "name": "eduActiv8",
      "website": "https://www.eduactiv8.org/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/optikey.json
{
  "name": "OptiKey",
  "description": "OptiKey - Full computer control and speech with your eyes.",
  "website": "",
  "license": [
    {
      "spdx": "GPL-3.0",
      "licenseURL": "https://github.com/OptiKey/OptiKey/blob/master/LICENSE.txt"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 3
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/OptiKey/OptiKey",
  "organizations": [
    {
      "name": "OptiKey",
      "website": "https://www.optikey.org",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/project-catalog-management-tool.json
{
  "name": "Project Catalog Management Tool",
  "aliases": [
    "PCMT"
  ],
  "description": "PCMT is open source software that allows organizations to publish and manage product catalogs.  It supports GS1 standards for identifying products, capturing data from barcodes, and sharing data. PCMT also acts as a OpenHIE Product Registry, sharing master product data to enable interoperability across eHealth ecosystems.",
  "website": "https://pcmt.gitlab.io/website/",
  "license": [
    {
      "spdx": "NPOSL-3.0",
      "licenseURL": "https://gitlab.com/pcmt/pcmt/-/blob/master/LICENSE"
    },
    {
      "spdx": "CC-BY-SA-4.0",
      "licenseURL": "https://gitlab.com/pcmt/pcmt/-/blob/master/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 16
    },
    {
      "SDGNumber": 17
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://gitlab.com/pcmt/pcmt",
  "organizations": [
    {
      "name": "VillageReach",
      "website": "https://www.villagereach.org/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/mifos-community-app.json
{
  "name": "Mifos Community App",
  "description": "This is the default web application built on top of the MifosX platform for the mifos user community.",
  "website": "https://mifos.org",
  "license": [
    {
      "spdx": "MPL-2.0",
      "licenseURL": "https://github.com/openMF/community-app/blob/develop/LICENSE.txt"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 1
    },
    {
      "SDGNumber": 10
    },
    {
      "SDGNumber": 11
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/openMF/community-app",
  "organizations": [
    {
      "name": "Mifos",
      "website": "https://mifos.org",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/octopus-microfinance.json
{
  "name": "Octopus Microfinance",
  "description": "Comprehensive Management Information Systems (MIS) for Microfinance: loans and savings portfolio management, interactive client relationship management, integrated accounting and proactive risk management.",
  "website": "https://sourceforge.net/projects/omfs/",
  "license": [
    {
      "spdx": "LGPL-3.0",
      "licenseURL": "https://sourceforge.net/projects/omfs/"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 16
    },
    {
      "SDGNumber": 17
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://sourceforge.net/projects/omfs/",
  "organizations": [
    {
      "name": "Octopus Microfinance",
      "website": "https://sourceforge.net/projects/omfs/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/caltrack.json
{
  "name": "CalTRACK",
  "description": "CalTRACK methods describe a process of arriving at a calculation of avoided energy use.",
  "website": "https://docs.caltrack.org/en/latest/",
  "license": [
    {
      "spdx": "CC0-1.0",
      "licenseURL": "https://github.com/energy-market-methods/caltrack/blob/master/LICENSE"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 7
    }
  ],
  "sectors": [],
  "type": [
    "standard"
  ],
  "repositoryURL": "https://github.com/energy-market-methods/caltrack",
  "organizations": [
    {
      "name": "Energy Market Methods",
      "website": "https://www.energymarketmethods.org/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}

=== DPGAlliance/publicgoods-candidates/nominees/tideline.json
{
  "name": "TideLine",
  "description": "Library for Tidepool's timeline-style diabetes data visualization(s) used in Blip.",
  "website": "",
  "license": [
    {
      "spdx": "BSD-2-Clause",
      "licenseURL": "https://github.com/tidepool-org/tideline/blob/develop/license.txt"
    }
  ],
  "SDGs": [
    {
      "SDGNumber": 3
    }
  ],
  "sectors": [],
  "type": [
    "software"
  ],
  "repositoryURL": "https://github.com/tidepool-org/tideline",
  "organizations": [
    {
      "name": "TidePool",
      "website": "https://tidepool.org/",
      "org_type": "owner"
    }
  ],
  "stage": "nominee"
}
