=== DPGAlliance/publicgoods-candidates/screening-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "",
  "$comment": "Digital Public Good Metaschema: JSON Schema",
  "type": "object",
  "title": "Digital Public Good",
  "required": [
    "name",
    "clearOwnership",
    "platformIndependence",
    "documentation",
    "NonPII",
    "locations",
    "privacy",
    "standards",
    "doNoHarm"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the Digital Public Good."
    },
    "clearOwnership": {
      "type": "object",
      "description": "3. Is ownership clearly defined?",
      "required": [
        "isOwnershipExplicit"
      ],
      "properties": {
        "isOwnershipExplicit": {
          "type": "string",
          "description": "Is the ownership of the project and everything that the project produces clearly defined and documented?",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown"
          ]
        },
        "copyrightURL": {
          "type": "string",
          "description": "If yes - please link to the relevant copyright, trademarks, or ownership documentation for the project."
        }
      }
    },
    "platformIndependence": {
      "type": "object",
      "description": "4. Does the license of libraries/dependencies undermine the openess of the project?",
      "required": [
        "mandatoryDepsCreateMoreRestrictions"
      ],
      "properties": {
        "mandatoryDepsCreateMoreRestrictions": {
          "type": "string",
          "description": "Does this open project have mandatory dependencies (i.e. libraries, hardware) that create more restrictions than the original license?",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown"
          ]
        },
        "isSoftwarePltIndependent": {
          "type": "string",
          "description": "If yes - are the open source components able to demonstrate independence from the closed component(s) and/or are there functional, open alternatives?",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown",
            ""
          ]
        },
        "pltIndependenceDesc": {
          "type": "string",
          "description": "If yes - please describe how the open source components are independent and/or list the open alternatives for the closed component:"
        }
      }
    },
    "documentation": {
      "type": "object",
      "description": "5. Is there documentation?",
      "required": [
        "isDocumentationAvailable"
      ],
      "properties": {
        "isDocumentationAvailable": {
          "type": "string",
          "description": "Does some documentation exist of the source code, use cases, and/or functional requirements.\n For software projects, this should be present as technical documentation that would allow a technical person unfamiliar with the project to launch and run the software. For data projects, this should be present as documentation that describes all the fields in the set, and provides context on how the data was collected and how it should be interpreted. For content, this should indicate any relevant compatible apps, software, hardware required to access the content and any instructions about how to use it.",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown"
          ]
        },
        "documentationURL": {
          "type": "array",
          "description": "If yes - please link to the relevant documentation:",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        }
      }
    },
    "NonPII": {
      "type": "object",
      "description": "6. Is non PII data accessible?",
      "required": [
        "collectsNonPII"
      ],
      "properties": {
        "collectsNonPII": {
          "type": "string",
          "description": "Does this project collect or use non-personally identifiable information (non-PII) data?",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown"
          ]
        },
        "checkNonPIIAccessMechanism": {
          "type": "string",
          "description": "If yes - is there a mechanism for extracting or importing non-personally identifiable information (non-PII) from the system in a non-proprietary format?",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown",
            ""
          ]
        },
        "nonPIIAccessMechanism": {
          "type": "string",
          "description": "If yes - describe the mechanism for extracting or importing non-personally identifiable information from the system in a non-proprietary format:"
        }
      }
    },
    "privacy": {
      "type": "object",
      "description": "7. Does the project adhere to privacy and other applicable international and domestic laws?",
      "required": [
        "isPrivacyCompliant"
      ],
      "properties": {
        "isPrivacyCompliant": {
          "type": "string",
          "description": "Has this project taken steps to ensure adherence with relevant privacy, domestic, and international laws? For example, the General Data Protection Regulation (GDPR) in the European Union or the Supplementary Act A/SA.1/01/10 on Personal Data Protection for the Economic Community of West African States (ECOWAS) (yes/no)",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown"
          ]
        },
        "privacyComplianceList": {
          "type": "array",
          "description": "If yes, please list some of relevant laws that the project complies with:",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        },
        "adherenceSteps": {
          "type": "array",
          "description": "If yes, please describe the steps this project has taken to ensure adherence (include links to terms of service, privacy policy, or other relevant documentation):",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        }
      }
    },
    "standards": {
      "type": "object",
      "description": "8. Does the project adhere to standards and best practices?",
      "required": [
        "supportStandards",
        "implementBestPractices"
      ],
      "properties": {
        "supportStandards": {
          "type": "string",
          "description": "Does this project support standards? (i.e. Web Content Accessibility Guidelines (WCAG) 2.1 or other standards such as those listed on W3C)",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown"
          ]
        },
        "standardsList": {
          "type": "array",
          "description": "Which standards does this project support (please list)",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        },
        "evidenceStandardSupport": {
          "type": "array",
          "description": "Can you point to evidence of your support? (i.e. please link to your validator, open test suite, etc.)",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        },
        "implementBestPractices": {
          "type": "string",
          "description": "Was this project built and developed according to or in adherence with any design, technical and/or sector best practices or principles? i.e. the Principles for Digital Development?"
        },
        "bestPracticesList": {
          "type": "array",
          "description": "Which principles and best practices does this project support (please list)",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        }
      }
    },
    "doNoHarm": {
      "type": "object",
      "description": "9. Does the project do no harm?",
      "required": [
        "preventHarm",
        "dataPrivacySecurity",
        "inappropriateIllegalContent",
        "protectionFromHarassment"
      ],
      "properties": {
        "preventHarm": {
          "type": "object",
          "description": "Has this project taken steps to anticipate, prevent and do no harm?",
          "required": [
            "stepsToPreventHarm"
          ],
          "properties": {
            "stepsToPreventHarm": {
              "type": "string",
              "description": "On the whole, does this project take steps to ensure that it anticipates, prevents and does no harm?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown"
              ]
            },
            "additionalInfoMechanismProcessesPolicies": {
              "type": "string",
              "description": "Is there any additional information you would like to share about the mechanisms, processes or policies that this project uses to avoid doing harm?"
            }
          }
        },
        "dataPrivacySecurity": {
          "type": "object",
          "description": "9.a. Data Privacy & Security",
          "required": [
            "collectsPII"
          ],
          "properties": {
            "collectsPII": {
              "type": "string",
              "description": "Does this project collect or store personally identifiable information (PII) data?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown"
              ]
            },
            "typesOfDataCollected": {
              "type": "array",
              "description": "If yes - please list the types of data collected and/or stored by the project:",
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              }
            },
            "thirdPartyDataSharing": {
              "type": "string",
              "description": "If yes - does this project share this data with third parties?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown"
              ]
            },
            "dataSharingCircumstances": {
              "type": "array",
              "description": "Please describe the circumstances with which this project shares data with third parties. Please add links as relevant.",
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              }
            },
            "ensurePrivacySecurity": {
              "type": "string",
              "description": "If yes - does the project ensure the privacy and security of this data and has it taken steps to prevent adverse impacts resulting from its collection, storage and distribution.",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown"
              ]
            },
            "privacySecurityDescription": {
              "type": "string",
              "description": "If yes - please describe the steps, and include a link to the privacy policy and/or terms of service:"
            }
          }
        },
        "inappropriateIllegalContent": {
          "type": "object",
          "description": "9.b. Inappropriate & Illegal Content",
          "required": [
            "collectStoreDistribute"
          ],
          "properties": {
            "collectStoreDistribute": {
              "type": "string",
              "description": "Does this project collect, store or distribute content?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown"
              ]
            },
            "type": {
              "contentType": "string",
              "description": "If yes - what kinds of content does this project, collect, store or distribute? (i.e. childrens books)"
            },
            "contentFilter": {
              "type": "string",
              "description": "If yes - does this project have policies that describe what is considered innappropriate content? (i.e. child sexual abuse materials)",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown",
                ""
              ]
            },
            "policyGuidelinesDocumentationLink": {
              "type": "string",
              "description": "If yes - please link to the relevant policy/guidelines/documentation."
            },
            "illegalContentDetection": {
              "type": "string",
              "description": "If yes - does this project have mechanisms for detecting and moderating innappropriate/illegal content?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown",
                ""
              ]
            },
            "illegalContentDetectionMechanism": {
              "type": "string",
              "description": "If yes - please describe the mechanism for detecting, reporting and removing innapropriate/illegal content (Please include the average response time for assessment and/or action. Link to any policies or descriptions of how inappropriate content is handled):"
            }
          }
        },
        "protectionFromHarassment": {
          "type": "object",
          "description": "9.c. Protection from harassment",
          "required": [
            "userInteraction"
          ],
          "properties": {
            "userInteraction": {
              "type": "string",
              "description": "Does this project facilitate interactions with or between users or contributors?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown"
              ]
            },
            "addressSafetySecurityUnderageUsers": {
              "type": "string",
              "description": "If yes - does the project take steps to address the safety and security of underage users?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown",
                ""
              ]
            },
            "stepsAddressRiskPreventSafetyUnderageUsers": {
              "type": "array",
              "description": "If yes - please describe the steps this project takes to address risk or prevent access by underage users:",
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              }
            },
            "griefAbuseHarassmentProtection": {
              "type": "string",
              "description": "If yes - does the project help users and contributors protect themselves against grief, abuse, and harassment?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown",
                ""
              ]
            },
            "harassmentProtectionSteps": {
              "type": "array",
              "description": "If yes - please describe the steps taken to help users protect themselves.",
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "locations": {
      "type": "object",
      "description": "Development & deployment countries",
      "required": [
        "developmentCountries",
        "deploymentCountries"
      ],
      "properties": {
        "developmentCountries": {
          "type": "array",
          "description": "List of countries this project was developed in.",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        },
        "deploymentCountries": {
          "type": "array",
          "description": "List of countries this project is actively deployed in.",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        }
      }
    }
  }
}

=== DPGAlliance/publicgoods-candidates/digitalpublicgoods/safe-you.json
{
  "name": "Safe YOU",
  "clearOwnership": {
    "isOwnershipExplicit": "Yes",
    "copyrightURL": "https://www.linkedin.com/showcase/safe-you"
  },
  "platformIndependence": {
    "mandatoryDepsCreateMoreRestrictions": "No",
    "isSoftwarePltIndependent": "",
    "pltIndependenceDesc": ""
  },
  "documentation": {
    "isDocumentationAvailable": "Yes",
    "documentationURL": [
      "https://github.com/safeyou-space/safeyou/blob/main/README.md"
    ]
  },
  "NonPII": {
    "collectsNonPII": "Yes",
    "checkNonPIIAccessMechanism": "Yes",
    "nonPIIAccessMechanism": "Extraction of non PII is made through a manual mechanism from database. It still remains a restricted information and can be extracted only by authorized personnel."
  },
  "privacy": {
    "isPrivacyCompliant": "Yes",
    "privacyComplianceList": [
      "The Project is currently active in Armenia and Georgia. Our Policies comply with Domestic information Security laws, both in Armenia and Georgia. More specifically, this refers to “RA Civil Code” adopted on 5 May 1998, “RA Law on protection of personal data” adopted on 18 May 2015. For Georgia: \"Law of Georgia on Information Security\" adopted on 01/07/2012. We are currently reviewing our policies to comply with GDPR."
    ],
    "adherenceSteps": [
      "https://docs.google.com/document/d/1OMw2OnSP-_SaXWai7kZzPeqd71RrQo2VEP_T2NUxazo/edit?usp=sharing https://docs.google.com/document/d/1Px4lfHdbUUzgH5tEW2AyQOkvorPPOau7NglPfZdBEdA/edit?usp=sharing"
    ]
  },
  "standards": {
    "supportStandards": "Yes",
    "standardsList": [
      "Web DEsign and Applications: HTML, CSS",
      "Web Architecture: URIs",
      "Web of Services: HTTP, REST, JSON"
    ],
    "evidenceStandardSupport": [
      "https://github.com/safeyou-space/safeyou/blob/main/README.md"
    ],
    "implementBestPractices": "Yes",
    "bestPracticesList": [
      "Principles for Digital Development"
    ]
  },
  "doNoHarm": {
    "preventHarm": {
      "stepsToPreventHarm": "Yes",
      "additionalInfoMechanismProcessesPolicies": "Since the usage of the mobile App may itself become a problem for already vulnerable groups, we have created two advanced security layers to minimize the risk of abusers discovering the app: a Dual PIN and a camouflage icon setting. The Dual PIN acts as a safety measure, allowing users to create a real PIN to access the app and a fake PIN that displays a photo gallery. The camouflage setting hides the app icon by displaying it as an image editing app so that women can use the app without fear of reprisal. The content in Forums is generated through our organization's content creators and by the personnel of governmental and non-governmental organizations who are partnering with us and have access to the tools of content generation and management. Contributors of the Forums section are thoroughly chosen making sure that they adhere to the general principle of “Do no harm”, while they create content and/or consult adolescent girls and women. Our Partner organizations are responsible to make sure that their engaged personnel acts appropriately e.g.: \n- Avoids questions, attitudes or comments that are judgmental or insensitive to cultural values or status; \n -Does not use language, make suggestions, provide misleading information or offer advice, which is inappropriate, offensive or abusive. \n In the Forums users engage with each other in discussions and can ask questions  to our partner organizations or to verified consultants, who are identifiable in the forums by a “verified badge”. That is why we clearly define in our Terms and Conditions and relevant policies that the users should refrain from abusing, threatening or otherwise violating the rights of others they are not allowed to publish, post, distribute or disseminate any inappropriate, threatening, infringing, obscene or unlawful topic, material or information. To adhere the principle of “Do no harm” we have moderation access in our “Forums” section, which permits our partner organizations to moderate and remove content (user comments) that violates our terms, in some cases (when the users continue acting the same way after two notifications) the moderators have the right to block the users, who create content violating our terms. For now, the moderation in the platform is done manually by moderating the content daily. We are also currently working on functionality so that the users and contributors can report the abusive comments from mobile App and management dashboard, respectively. \n The Terms and Conditions as well as our Privacy Policies clearly describe these circumstances, and the users give consent to such data sharing."
    },
    "dataPrivacySecurity": {
      "collectsPII": "Yes",
      "typesOfDataCollected": [
        "Name",
        "Surname",
        "mobile number",
        "marital status (non compulsory)",
        "birthdate",
        "geolocation (when help function is used)",
        "e-mail (when an e-mail is sent to third parties through our platform)."
      ],
      "thirdPartyDataSharing": "Yes",
      "dataSharingCircumstances": [
        "User's name, surname, mobile number, and geolocation are shared with the prechosen contacts: when the user is in danger, she can press the help button of the App, this will send a free alert SMS, with user's Name, Surname, and geolocation to up to 7 directions of prechosen contacts to let them know that the user is in danger. These contacts may be anyone from user's phone's contacts list, NGOs or state authorities that are included in our Apps 'Network' section, as well as the Police, if the 'Contact Police' function is enabled by the user."
      ],
      "ensurePrivacySecurity": "Yes",
      "privacySecurityDescription": "We ensure the security of collected data both by technical and policy means, more specifically the number of personnel, who has access to such data is strictly limited, moreover all the personnel has signed non-disclosure agreementS (NDAs), which clearly define user’s personal data as a confidential information subject to confidentiality terms, the NDAs also imply strict monetary penalties in case of breach. \n As to the technical level of ensuring security of the data, we use SSL certificates, database connection is private -> connection to the DB is available only via local server (outbound connections are disabled)."
    },
    "inappropriateIllegalContent": {
      "collectStoreDistribute": "Yes",
      "type": "The content in forums are related to vast variety of topics that may interest women (e.g. reproductive health, psychological help, parenting, maternity, law etc.)",
      "contentFilter": "Yes",
      "policyGuidelinesDocumentationLink": "We have included the list (non-exhaustive) of inappropriate content that is not allowed to be distributed through Safe YOU in Ground Rules section of our Terms and Conditions: https://docs.google.com/document/d/1Px4lfHdbUUzgH5tEW2AyQOkvorPPOau7NglPfZdBEdA/edit",
      "illegalContentDetection": "Yes",
      "illegalContentDetectionMechanism": "We have moderators, who are monitoring users’ comments on a daily basis and reviewing their compliance to our general terms. If an inappropriate content is detected, the author of the content is warned that the comment does not correspond to our ground rules, and it should be removed by moderator. \n The users and contributors themselves have the option to contact moderator through e-mail to report the abusive content. The response time usually varies from 24-48 hours. Currently we are developing tools for users and contributors to report comments, which they find inappropriate. \n Our Terms and conditions state that Safe YOU can review user’s conduct and content for compliance with the T&C and reserves the right to remove any violating content."
    },
    "protectionFromHarassment": {
      "userInteraction": "Yes",
      "addressSafetySecurityUnderageUsers": "Yes",
      "stepsAddressRiskPreventSafetyUnderageUsers": [
        "The users can access the content in “Forums” section of the Mobile app, if the content has age restrictions it should be clearly mentioned both in the subject of the Forum and in its banner photo. No age specific age restrictions have been made so far (e.g., blocking limiting access to relevant content for users under specific age). The Project team is currently working on creating a separate environment for users under the age 18."
      ],
      "griefAbuseHarassmentProtection": "Yes",
      "harassmentProtectionSteps": [
        "The users and contributors can contact project team and report the issues that they have had related to the App or the content. As mentioned above we are currently working on developing tools for users and contributors to be able to report the content, which they find harassing.",
        "Our users are encouraged to hide their identity when they interact in forums with contributors and other users, this is to ensure the anonymity and safety of the users themselves."
      ]
    }
  },
  "locations": {
    "developmentCountries": [
      "Armenia"
    ],
    "deploymentCountries": [
      "Armenia",
      "Georgia"
    ]
  }
}
