=== DPGAlliance/publicgoods-candidates/screening-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "",
  "$comment": "Digital Public Good Metaschema: JSON Schema",
  "type": "object",
  "title": "Digital Public Good",
  "required": [
    "name",
    "clearOwnership",
    "platformIndependence",
    "documentation",
    "NonPII",
    "locations",
    "privacy",
    "standards",
    "doNoHarm"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the Digital Public Good."
    },
    "clearOwnership": {
      "type": "object",
      "description": "3. Is ownership clearly defined?",
      "required": [
        "isOwnershipExplicit"
      ],
      "properties": {
        "isOwnershipExplicit": {
          "type": "string",
          "description": "Is the ownership of the project and everything that the project produces clearly defined and documented?",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown"
          ]
        },
        "copyrightURL": {
          "type": "string",
          "description": "If yes - please link to the relevant copyright, trademarks, or ownership documentation for the project."
        }
      }
    },
    "platformIndependence": {
      "type": "object",
      "description": "4. Does the license of libraries/dependencies undermine the openess of the project?",
      "required": [
        "mandatoryDepsCreateMoreRestrictions"
      ],
      "properties": {
        "mandatoryDepsCreateMoreRestrictions": {
          "type": "string",
          "description": "Does this open project have mandatory dependencies (i.e. libraries, hardware) that create more restrictions than the original license?",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown"
          ]
        },
        "isSoftwarePltIndependent": {
          "type": "string",
          "description": "If yes - are the open source components able to demonstrate independence from the closed component(s) and/or are there functional, open alternatives?",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown",
            ""
          ]
        },
        "pltIndependenceDesc": {
          "type": "string",
          "description": "If yes - please describe how the open source components are independent and/or list the open alternatives for the closed component:"
        }
      }
    },
    "documentation": {
      "type": "object",
      "description": "5. Is there documentation?",
      "required": [
        "isDocumentationAvailable"
      ],
      "properties": {
        "isDocumentationAvailable": {
          "type": "string",
          "description": "Does some documentation exist of the source code, use cases, and/or functional requirements.\n For software projects, this should be present as technical documentation that would allow a technical person unfamiliar with the project to launch and run the software. For data projects, this should be present as documentation that describes all the fields in the set, and provides context on how the data was collected and how it should be interpreted. For content, this should indicate any relevant compatible apps, software, hardware required to access the content and any instructions about how to use it.",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown"
          ]
        },
        "documentationURL": {
          "type": "array",
          "description": "If yes - please link to the relevant documentation:",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        }
      }
    },
    "NonPII": {
      "type": "object",
      "description": "6. Is non PII data accessible?",
      "required": [
        "collectsNonPII"
      ],
      "properties": {
        "collectsNonPII": {
          "type": "string",
          "description": "Does this project collect or use non-personally identifiable information (non-PII) data?",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown"
          ]
        },
        "checkNonPIIAccessMechanism": {
          "type": "string",
          "description": "If yes - is there a mechanism for extracting or importing non-personally identifiable information (non-PII) from the system in a non-proprietary format?",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown",
            ""
          ]
        },
        "nonPIIAccessMechanism": {
          "type": "string",
          "description": "If yes - describe the mechanism for extracting or importing non-personally identifiable information from the system in a non-proprietary format:"
        }
      }
    },
    "privacy": {
      "type": "object",
      "description": "7. Does the project adhere to privacy and other applicable international and domestic laws?",
      "required": [
        "isPrivacyCompliant"
      ],
      "properties": {
        "isPrivacyCompliant": {
          "type": "string",
          "description": "Has this project taken steps to ensure adherence with relevant privacy, domestic, and international laws? For example, the General Data Protection Regulation (GDPR) in the European Union or the Supplementary Act A/SA.1/01/10 on Personal Data Protection for the Economic Community of West African States (ECOWAS) (yes/no)",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown"
          ]
        },
        "privacyComplianceList": {
          "type": "array",
          "description": "If yes, please list some of relevant laws that the project complies with:",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        },
        "adherenceSteps": {
          "type": "array",
          "description": "If yes, please describe the steps this project has taken to ensure adherence (include links to terms of service, privacy policy, or other relevant documentation):",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        }
      }
    },
    "standards": {
      "type": "object",
      "description": "8. Does the project adhere to standards and best practices?",
      "required": [
        "supportStandards",
        "implementBestPractices"
      ],
      "properties": {
        "supportStandards": {
          "type": "string",
          "description": "Does this project support standards? (i.e. Web Content Accessibility Guidelines (WCAG) 2.1 or other standards such as those listed on W3C)",
          "uniqueItems": true,
          "enum": [
            "Yes",
            "No",
            "Unknown"
          ]
        },
        "standardsList": {
          "type": "array",
          "description": "Which standards does this project support (please list)",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        },
        "evidenceStandardSupport": {
          "type": "array",
          "description": "Can you point to evidence of your support? (i.e. please link to your validator, open test suite, etc.)",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        },
        "implementBestPractices": {
          "type": "string",
          "description": "Was this project built and developed according to or in adherence with any design, technical and/or sector best practices or principles? i.e. the Principles for Digital Development?"
        },
        "bestPracticesList": {
          "type": "array",
          "description": "Which principles and best practices does this project support (please list)",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        }
      }
    },
    "doNoHarm": {
      "type": "object",
      "description": "9. Does the project do no harm?",
      "required": [
        "preventHarm",
        "dataPrivacySecurity",
        "inappropriateIllegalContent",
        "protectionFromHarassment"
      ],
      "properties": {
        "preventHarm": {
          "type": "object",
          "description": "Has this project taken steps to anticipate, prevent and do no harm?",
          "required": [
            "stepsToPreventHarm"
          ],
          "properties": {
            "stepsToPreventHarm": {
              "type": "string",
              "description": "On the whole, does this project take steps to ensure that it anticipates, prevents and does no harm?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown"
              ]
            },
            "additionalInfoMechanismProcessesPolicies": {
              "type": "string",
              "description": "Is there any additional information you would like to share about the mechanisms, processes or policies that this project uses to avoid doing harm?"
            }
          }
        },
        "dataPrivacySecurity": {
          "type": "object",
          "description": "9.a. Data Privacy & Security",
          "required": [
            "collectsPII"
          ],
          "properties": {
            "collectsPII": {
              "type": "string",
              "description": "Does this project collect or store personally identifiable information (PII) data?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown"
              ]
            },
            "typesOfDataCollected": {
              "type": "array",
              "description": "If yes - please list the types of data collected and/or stored by the project:",
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              }
            },
            "thirdPartyDataSharing": {
              "type": "string",
              "description": "If yes - does this project share this data with third parties?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown"
              ]
            },
            "dataSharingCircumstances": {
              "type": "array",
              "description": "Please describe the circumstances with which this project shares data with third parties. Please add links as relevant.",
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              }
            },
            "ensurePrivacySecurity": {
              "type": "string",
              "description": "If yes - does the project ensure the privacy and security of this data and has it taken steps to prevent adverse impacts resulting from its collection, storage and distribution.",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown"
              ]
            },
            "privacySecurityDescription": {
              "type": "string",
              "description": "If yes - please describe the steps, and include a link to the privacy policy and/or terms of service:"
            }
          }
        },
        "inappropriateIllegalContent": {
          "type": "object",
          "description": "9.b. Inappropriate & Illegal Content",
          "required": [
            "collectStoreDistribute"
          ],
          "properties": {
            "collectStoreDistribute": {
              "type": "string",
              "description": "Does this project collect, store or distribute content?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown"
              ]
            },
            "type": {
              "contentType": "string",
              "description": "If yes - what kinds of content does this project, collect, store or distribute? (i.e. childrens books)"
            },
            "contentFilter": {
              "type": "string",
              "description": "If yes - does this project have policies that describe what is considered innappropriate content? (i.e. child sexual abuse materials)",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown",
                ""
              ]
            },
            "policyGuidelinesDocumentationLink": {
              "type": "string",
              "description": "If yes - please link to the relevant policy/guidelines/documentation."
            },
            "illegalContentDetection": {
              "type": "string",
              "description": "If yes - does this project have mechanisms for detecting and moderating innappropriate/illegal content?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown",
                ""
              ]
            },
            "illegalContentDetectionMechanism": {
              "type": "string",
              "description": "If yes - please describe the mechanism for detecting, reporting and removing innapropriate/illegal content (Please include the average response time for assessment and/or action. Link to any policies or descriptions of how inappropriate content is handled):"
            }
          }
        },
        "protectionFromHarassment": {
          "type": "object",
          "description": "9.c. Protection from harassment",
          "required": [
            "userInteraction"
          ],
          "properties": {
            "userInteraction": {
              "type": "string",
              "description": "Does this project facilitate interactions with or between users or contributors?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown"
              ]
            },
            "addressSafetySecurityUnderageUsers": {
              "type": "string",
              "description": "If yes - does the project take steps to address the safety and security of underage users?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown",
                ""
              ]
            },
            "stepsAddressRiskPreventSafetyUnderageUsers": {
              "type": "array",
              "description": "If yes - please describe the steps this project takes to address risk or prevent access by underage users:",
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              }
            },
            "griefAbuseHarassmentProtection": {
              "type": "string",
              "description": "If yes - does the project help users and contributors protect themselves against grief, abuse, and harassment?",
              "uniqueItems": true,
              "enum": [
                "Yes",
                "No",
                "Unknown",
                ""
              ]
            },
            "harassmentProtectionSteps": {
              "type": "array",
              "description": "If yes - please describe the steps taken to help users protect themselves.",
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "locations": {
      "type": "object",
      "description": "Development & deployment countries",
      "required": [
        "developmentCountries",
        "deploymentCountries"
      ],
      "properties": {
        "developmentCountries": {
          "type": "array",
          "description": "List of countries this project was developed in.",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        },
        "deploymentCountries": {
          "type": "array",
          "description": "List of countries this project is actively deployed in.",
          "items": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          }
        }
      }
    }
  }
}

=== DPGAlliance/publicgoods-candidates/digitalpublicgoods/geoprism-registry.json
{
  "name": "GeoPrism Registry",
  "clearOwnership": {
    "isOwnershipExplicit": "Yes",
    "copyrightURL": "https://www.terraframe.com/products"
  },
  "platformIndependence": {
    "mandatoryDepsCreateMoreRestrictions": "No",
    "isSoftwarePltIndependent": "",
    "pltIndependenceDesc": ""
  },
  "documentation": {
    "isDocumentationAvailable": "Yes",
    "documentationURL": [
      "https://georegistry-api-docs.geoprism.net",
      "https://geoprismregistry.com/",
      "Developer documentation - https://github.com/terraframe/geoprism-registry/wiki",
      "Installation guide (without docker) - https://github.com/terraframe/geoprism-registry/wiki/Install-on-Linux-or-Mac"
    ]
  },
  "NonPII": {
    "collectsNonPII": "Yes",
    "checkNonPIIAccessMechanism": "Yes",
    "nonPIIAccessMechanism": "Here is the documentation for importing data using non-proprietary formats - https://docs.geoprismregistry.com/readme/current/geoprism-registry-tutorial/6.5-content-management/6.5.1-lists-and-spatial-data/6.5.1.1-import \nHere is the documentation for exporting data using non-proprietary formats - https://docs.geoprismregistry.com/readme/current/geoprism-registry-tutorial/6.5-content-management/6.5.1-lists-and-spatial-data/6.5.1.7-export \nHere is the API documentation for getting data in JSON format - https://api.geoprismregistry.com/#tag/List/operation/data \nThat site also documents how to import data in GeoJSON format."
  },
  "privacy": {
    "isPrivacyCompliant": "Yes",
    "privacyComplianceList": [
      "GeoPrism Registry does not manage personal data, but rather lists, hierarchies and geospatial data curated by the ministries with the authoritative mandate. This includes administrative divisions, villages, infrastructure, and other relevant physical and virtual features."
    ],
    "adherenceSteps": [
      "Documentation on the user roles to ensure only the organizations with the authoritative mandate can make data public: https://terraframe.atlassian.net/wiki/spaces/GGR/pages/931004419/User+Management"
    ]
  },
  "standards": {
    "supportStandards": "Yes",
    "standardsList": [
      "OAuth 2",
      "SAML",
      "UTF-8",
      "HTML",
      "CSS",
      "ECMAScript",
      "REST",
      "OpenAPI",
      "JSON",
      "GeoJSON",
      "XML",
      "VectorTiles"
    ],
    "evidenceStandardSupport": [
      "https://github.com/terraframe/geoprism-registry/tree/master/georegistry-test"
    ],
    "implementBestPractices": "Yes",
    "bestPracticesList": [
      "Understand the Existing Ecosystem, Design for Scale, Build for Sustainability, Be Data Driven, Use Open Standards, Open Source and Open Innovation, Reuse and Improve, Address Privacy & Security, Be Collaborative"
    ]
  },
  "doNoHarm": {
    "preventHarm": {
      "stepsToPreventHarm": "Yes",
      "additionalInfoMechanismProcessesPolicies": "A multi-tenant architecture and role-based access controls ensure that only the organizations with the authoritative mandate can share and make public geospatial data. Changes to data are supervised through change request management workflow to ensure sensitive data are not made public."
    },
    "dataPrivacySecurity": {
      "collectsPII": "No",
      "typesOfDataCollected": [
        ""
      ],
      "thirdPartyDataSharing": "No",
      "dataSharingCircumstances": [
        ""
      ],
      "ensurePrivacySecurity": "Yes",
      "privacySecurityDescription": "GeoPrism Registry does not manage personal data, but rather lists, hierarchies and geospatial data curated by the ministries with the authoritative mandate. This includes administrative divisions, villages, infrastructure, and other relevant physical and virtual features."
    },
    "inappropriateIllegalContent": {
      "collectStoreDistribute": "No",
      "type": "",
      "contentFilter": "",
      "policyGuidelinesDocumentationLink": "",
      "illegalContentDetection": "",
      "illegalContentDetectionMechanism": ""
    },
    "protectionFromHarassment": {
      "userInteraction": "No",
      "addressSafetySecurityUnderageUsers": "",
      "stepsAddressRiskPreventSafetyUnderageUsers": [
        ""
      ],
      "griefAbuseHarassmentProtection": "",
      "harassmentProtectionSteps": [
        ""
      ]
    }
  },
  "locations": {
    "developmentCountries": [
      "United States of America"
    ],
    "deploymentCountries": [
      "Laos",
      "Mozambique",
      "United States of America"
    ]
  }
}

=== DPGAlliance/publicgoods-candidates/digitalpublicgoods/vaccineledger.json
{
  "name": "VaccineLedger",
  "clearOwnership": {
    "isOwnershipExplicit": "Yes",
    "copyrightURL": "https://gitlab.com/statwig-public/theledger/-/blob/6c3bf23524244bf0d2cf0a2772214a21d1a270ee/LICENSE"
  },
  "platformIndependence": {
    "mandatoryDepsCreateMoreRestrictions": "No",
    "isSoftwarePltIndependent": "",
    "pltIndependenceDesc": ""
  },
  "documentation": {
    "isDocumentationAvailable": "Yes",
    "documentationURL": [
      "https://gitlab.com/statwig-public/theledger",
      "https://gitlab.com/statwig-public/theledger/-/blob/6c3bf23524244bf0d2cf0a2772214a21d1a270ee/docs/VaccineLedger-_Use_Case___Functional_Features_.pdf",
      "https://gitlab.com/statwig-public/theledger/-/blob/6c3bf23524244bf0d2cf0a2772214a21d1a270ee/README.md"
    ]
  },
  "NonPII": {
    "collectsNonPII": "Yes",
    "checkNonPIIAccessMechanism": "Yes",
    "nonPIIAccessMechanism": "This data is stored on Blockchain and can be accessible through REST APIs.\nThe core idea of blockchain is collaboration based on shared data ownership, governance and  operations. The major difference from centralized system architectures is that peers,  collaborating in a network, can continue using their own systems and technology stack without  the need to integrate them in the classical way. Instead, blockchain provides a shared data  layer that allows these systems to interoperate on top and acts as the single truth. \n\nAs a result, the network has no single authority, which owns the data or controls the systems.  The decentralization of the ledger means a decentralization of power.\n\nLink to Evidence: https://gitlab.com/statwig-public/theledger/-/blob/development/docs/VaccineLedger_-_Data_Confidentiality.pdf"
  },
  "privacy": {
    "isPrivacyCompliant": "Yes",
    "privacyComplianceList": [
      "https://gitlab.com/statwig-public/theledger/-/blob/6c3bf23524244bf0d2cf0a2772214a21d1a270ee/docs/Server.pdf"
    ],
    "adherenceSteps": [
      "Privacy policy - https://gitlab.com/statwig-public/theledger/-/blob/development/docs/Privacy_policy_of_VaccineLedger__1_.pdf",
      "https://gitlab.com/statwig-public/theledger/-/blob/6c3bf23524244bf0d2cf0a2772214a21d1a270ee/docs/Server.pdf"
    ]
  },
  "standards": {
    "supportStandards": "Yes",
    "standardsList": [
      "WaSP",
      "HTML",
      "CSS",
      "ECMAScript",
      "JSON",
      "REST"
    ],
    "evidenceStandardSupport": [
      "https://gitlab.com/statwig-public/theledger/-/blob/development/docs/Standards"
    ],
    "implementBestPractices": "Yes",
    "bestPracticesList": [
      "Principles of Digital Development ",
      "https://gitlab.com/statwig-public/theledger/-/blob/development/docs/Standards"
    ]
  },
  "doNoHarm": {
    "preventHarm": {
      "stepsToPreventHarm": "Yes",
      "additionalInfoMechanismProcessesPolicies": "Our Risk Management strategy includes  Include risk management in our projects (Guidelines / Checklist/ Templates) Communicate risks to other stakeholders. Prioritize risks. Analyze risks with metrics. Implement risk responses as early as possible to avoid aggravating issues. Track them down regularly for compliance."
    },
    "dataPrivacySecurity": {
      "collectsPII": "Yes",
      "typesOfDataCollected": [
        "https://gitlab.com/statwig-public/theledger/-/blob/development/docs/VaccineLedger_-_Data_Confidentiality.pdf"
      ],
      "thirdPartyDataSharing": "No",
      "dataSharingCircumstances": [
        ""
      ],
      "ensurePrivacySecurity": "Yes",
      "privacySecurityDescription": "User information like phone and email are not stored - https://gitlab.com/statwig-public/theledger/-/blob/050a19d2c92a2836bfb9483941e5219e5b90be62/docs/VaccineLedger_-_Data_Confidentiality.pdf"
    },
    "inappropriateIllegalContent": {
      "collectStoreDistribute": "No",
      "type": "",
      "contentFilter": "",
      "policyGuidelinesDocumentationLink": "",
      "illegalContentDetection": "",
      "illegalContentDetectionMechanism": ""
    },
    "protectionFromHarassment": {
      "userInteraction": "Yes",
      "addressSafetySecurityUnderageUsers": "Yes",
      "stepsAddressRiskPreventSafetyUnderageUsers": [
        "The users on our platform are supply chain managers, operational teams, logistics partners and so on. The user onboarding in each of these different types of users is carried out by a two step process:",
        "- Step 1: User registers using name, official emails and/or phone numbers for verification and other identification details when needed. ",
        "- Step 2: An admin reviews and approves the users."
      ],
      "griefAbuseHarassmentProtection": "Yes",
      "harassmentProtectionSteps": [
        "The safety and wellbeing of those we work with is of paramount importance to us. This includes staff, and the people  we work  with. We  have a  zero-tolerance  approach towards all forms of unethical behavior. We  also  have  a  zero  tolerance  towards  bribes,  facilitation  payments,  tax  evasion  and  money laundering. We will do all we can to prevent financing or the support of terrorist organisations and will not appoint or employ anyone that could reasonably be suspected to be connected to a terrorist group. We will abide by all the Laws in all matters including those related to modern slavery.",
        "Code of conduct - https://gitlab.com/statwig-public/theledger/-/blob/development/CODE_OF_CONDUCT.md"
      ]
    }
  },
  "locations": {
    "developmentCountries": [
      "India"
    ],
    "deploymentCountries": [
      "Costa Rica",
      "India"
    ]
  }
}
